# Generated by Django 5.2.3 on 2025-06-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0003_requirement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='is_part_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='applicable_to',
            field=models.CharField(choices=[('faculty', 'Faculty Member'), ('chair', 'Department Chair'), ('part_timer', 'Part-time Faculty')], default='faculty', max_length=10),
        ),
    ]
