# Generated by Django 5.2.3 on 2025-06-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0004_facultymember_is_part_time_requirement_applicable_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancedocument',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty Member'), ('chair', 'Department Chair'), ('part_timer', 'Part-time Faculty')], max_length=10),
        ),
    ]
