# Generated by Django 5.2.3 on 2025-06-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0005_alter_clearancedocument_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ClearanceDocument',
        ),
    ]
